//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Transport.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Expense
    {
        public long ExpenseCode { get; set; }
        public Nullable<long> VehicleCode { get; set; }
        public Nullable<long> ServiceTypeCode { get; set; }
        public Nullable<long> SupplierTypeCode { get; set; }
        public Nullable<int> Qty { get; set; }
        public Nullable<decimal> Charge { get; set; }
        public string Remarks { get; set; }
        public Nullable<System.DateTime> ExpenseDate { get; set; }
        public Nullable<int> PaymentBy { get; set; }
        public Nullable<int> PaidTo { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    }
}
