//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Transport.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Job
    {
        public long JobCode { get; set; }
        public System.DateTime JobDate { get; set; }
        public string JobTime { get; set; }
        public string JobFrom { get; set; }
        public string JobTo { get; set; }
        public Nullable<long> JobVendorCode { get; set; }
        public Nullable<long> VehicleCode { get; set; }
        public Nullable<int> DrivingBy { get; set; }
        public string OutSource { get; set; }
        public Nullable<decimal> OutSourceAmount { get; set; }
        public string CustomerName { get; set; }
        public string ContactNo { get; set; }
        public string JobStatus { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public Nullable<decimal> Credit { get; set; }
        public Nullable<decimal> Cash { get; set; }
        public Nullable<int> CashInHand { get; set; }
        public Nullable<long> JobRequestCode { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<decimal> OutSourceAmountGiven { get; set; }
    }
}
