//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Transport.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobRequest
    {
        public long JobRequestCode { get; set; }
        public System.DateTime JobRequestDate { get; set; }
        public string JobRequestTime { get; set; }
        public string JobRequestFrom { get; set; }
        public string JobRequestTo { get; set; }
        public string CustomerName { get; set; }
        public string ContactNo { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public Nullable<int> NoOfPaxs { get; set; }
        public Nullable<int> NoOfBags { get; set; }
        public string JobRequestStatus { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
