//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Transport.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceType
    {
        public long ServiceTypeCode { get; set; }
        public string ServiceTypeName { get; set; }
        public Nullable<bool> Status { get; set; }
    }
}
