//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Transport.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class TransportEntities : DbContext
    {
        public TransportEntities()
            : base("name=TransportEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<JobStatu> JobStatus { get; set; }
        public virtual DbSet<JobVendor> JobVendors { get; set; }
        public virtual DbSet<ServiceType> ServiceTypes { get; set; }
        public virtual DbSet<TblDefaultMasterDetail> TblDefaultMasterDetails { get; set; }
        public virtual DbSet<TblDefaultMasterHeader> TblDefaultMasterHeaders { get; set; }
        public virtual DbSet<TblHomePage> TblHomePages { get; set; }
        public virtual DbSet<TblMenuMasterDetail> TblMenuMasterDetails { get; set; }
        public virtual DbSet<TblMenuMasterHeader> TblMenuMasterHeaders { get; set; }
        public virtual DbSet<TblMenuRoleMatrixAccess> TblMenuRoleMatrixAccesses { get; set; }
        public virtual DbSet<TblRoleMaster> TblRoleMasters { get; set; }
        public virtual DbSet<TblUserMaster> TblUserMasters { get; set; }
        public virtual DbSet<Vehicle> Vehicles { get; set; }
        public virtual DbSet<JobRequest> JobRequests { get; set; }
        public virtual DbSet<Job> Jobs { get; set; }
        public virtual DbSet<SupplierType> SupplierTypes { get; set; }
        public virtual DbSet<Expense> Expenses { get; set; }
    
        public virtual int sp_frm_Clear_Trxns()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_frm_Clear_Trxns");
        }
    
        public virtual ObjectResult<sp_frm_get_CashInHand_Report_Result> sp_frm_get_CashInHand_Report(Nullable<System.DateTime> transactionFrom, Nullable<System.DateTime> transactionTo)
        {
            var transactionFromParameter = transactionFrom.HasValue ?
                new ObjectParameter("TransactionFrom", transactionFrom) :
                new ObjectParameter("TransactionFrom", typeof(System.DateTime));
    
            var transactionToParameter = transactionTo.HasValue ?
                new ObjectParameter("TransactionTo", transactionTo) :
                new ObjectParameter("TransactionTo", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_frm_get_CashInHand_Report_Result>("sp_frm_get_CashInHand_Report", transactionFromParameter, transactionToParameter);
        }
    
        public virtual ObjectResult<sp_frm_get_Credit_Report_Result> sp_frm_get_Credit_Report(Nullable<System.DateTime> transactionFrom, Nullable<System.DateTime> transactionTo)
        {
            var transactionFromParameter = transactionFrom.HasValue ?
                new ObjectParameter("TransactionFrom", transactionFrom) :
                new ObjectParameter("TransactionFrom", typeof(System.DateTime));
    
            var transactionToParameter = transactionTo.HasValue ?
                new ObjectParameter("TransactionTo", transactionTo) :
                new ObjectParameter("TransactionTo", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_frm_get_Credit_Report_Result>("sp_frm_get_Credit_Report", transactionFromParameter, transactionToParameter);
        }
    
        public virtual ObjectResult<sp_frm_get_CreditCustomers_Report_Result> sp_frm_get_CreditCustomers_Report(Nullable<System.DateTime> transactionFrom, Nullable<System.DateTime> transactionTo)
        {
            var transactionFromParameter = transactionFrom.HasValue ?
                new ObjectParameter("TransactionFrom", transactionFrom) :
                new ObjectParameter("TransactionFrom", typeof(System.DateTime));
    
            var transactionToParameter = transactionTo.HasValue ?
                new ObjectParameter("TransactionTo", transactionTo) :
                new ObjectParameter("TransactionTo", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_frm_get_CreditCustomers_Report_Result>("sp_frm_get_CreditCustomers_Report", transactionFromParameter, transactionToParameter);
        }
    
        public virtual ObjectResult<sp_frm_get_Dashboard_Daily_Result> sp_frm_get_Dashboard_Daily(Nullable<int> customerId)
        {
            var customerIdParameter = customerId.HasValue ?
                new ObjectParameter("CustomerId", customerId) :
                new ObjectParameter("CustomerId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_frm_get_Dashboard_Daily_Result>("sp_frm_get_Dashboard_Daily", customerIdParameter);
        }
    
        public virtual int sp_frm_get_Dashboard_Report(Nullable<int> customerId, Nullable<System.DateTime> transactionFrom, Nullable<System.DateTime> transactionTo)
        {
            var customerIdParameter = customerId.HasValue ?
                new ObjectParameter("CustomerId", customerId) :
                new ObjectParameter("CustomerId", typeof(int));
    
            var transactionFromParameter = transactionFrom.HasValue ?
                new ObjectParameter("TransactionFrom", transactionFrom) :
                new ObjectParameter("TransactionFrom", typeof(System.DateTime));
    
            var transactionToParameter = transactionTo.HasValue ?
                new ObjectParameter("TransactionTo", transactionTo) :
                new ObjectParameter("TransactionTo", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_frm_get_Dashboard_Report", customerIdParameter, transactionFromParameter, transactionToParameter);
        }
    
        public virtual ObjectResult<sp_frm_get_Total_Report_Result> sp_frm_get_Total_Report(Nullable<System.DateTime> transactionFrom, Nullable<System.DateTime> transactionTo)
        {
            var transactionFromParameter = transactionFrom.HasValue ?
                new ObjectParameter("TransactionFrom", transactionFrom) :
                new ObjectParameter("TransactionFrom", typeof(System.DateTime));
    
            var transactionToParameter = transactionTo.HasValue ?
                new ObjectParameter("TransactionTo", transactionTo) :
                new ObjectParameter("TransactionTo", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_frm_get_Total_Report_Result>("sp_frm_get_Total_Report", transactionFromParameter, transactionToParameter);
        }
    
        public virtual ObjectResult<sp_frm_get_Vehicle_Expense_Report_Result> sp_frm_get_Vehicle_Expense_Report(Nullable<System.DateTime> transactionFrom, Nullable<System.DateTime> transactionTo, Nullable<long> vehicleCode)
        {
            var transactionFromParameter = transactionFrom.HasValue ?
                new ObjectParameter("TransactionFrom", transactionFrom) :
                new ObjectParameter("TransactionFrom", typeof(System.DateTime));
    
            var transactionToParameter = transactionTo.HasValue ?
                new ObjectParameter("TransactionTo", transactionTo) :
                new ObjectParameter("TransactionTo", typeof(System.DateTime));
    
            var vehicleCodeParameter = vehicleCode.HasValue ?
                new ObjectParameter("VehicleCode", vehicleCode) :
                new ObjectParameter("VehicleCode", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_frm_get_Vehicle_Expense_Report_Result>("sp_frm_get_Vehicle_Expense_Report", transactionFromParameter, transactionToParameter, vehicleCodeParameter);
        }
    
        public virtual ObjectResult<sp_frm_get_Vehicle_Report_Result> sp_frm_get_Vehicle_Report(Nullable<System.DateTime> transactionFrom, Nullable<System.DateTime> transactionTo)
        {
            var transactionFromParameter = transactionFrom.HasValue ?
                new ObjectParameter("TransactionFrom", transactionFrom) :
                new ObjectParameter("TransactionFrom", typeof(System.DateTime));
    
            var transactionToParameter = transactionTo.HasValue ?
                new ObjectParameter("TransactionTo", transactionTo) :
                new ObjectParameter("TransactionTo", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_frm_get_Vehicle_Report_Result>("sp_frm_get_Vehicle_Report", transactionFromParameter, transactionToParameter);
        }
    
        public virtual ObjectResult<sp_frm_get_Vehicle_Total_Report_Result> sp_frm_get_Vehicle_Total_Report(Nullable<System.DateTime> transactionFrom, Nullable<System.DateTime> transactionTo, Nullable<long> vehicleCode)
        {
            var transactionFromParameter = transactionFrom.HasValue ?
                new ObjectParameter("TransactionFrom", transactionFrom) :
                new ObjectParameter("TransactionFrom", typeof(System.DateTime));
    
            var transactionToParameter = transactionTo.HasValue ?
                new ObjectParameter("TransactionTo", transactionTo) :
                new ObjectParameter("TransactionTo", typeof(System.DateTime));
    
            var vehicleCodeParameter = vehicleCode.HasValue ?
                new ObjectParameter("VehicleCode", vehicleCode) :
                new ObjectParameter("VehicleCode", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_frm_get_Vehicle_Total_Report_Result>("sp_frm_get_Vehicle_Total_Report", transactionFromParameter, transactionToParameter, vehicleCodeParameter);
        }
    
        public virtual ObjectResult<sp_frm_get_Jobs_Result> sp_frm_get_Jobs(Nullable<long> vehicleCode, Nullable<long> jobVendorCode, string customerName, string contactNo, Nullable<int> drivingBy, Nullable<int> cashInHand, Nullable<System.DateTime> transactionFrom, Nullable<System.DateTime> transactionTo)
        {
            var vehicleCodeParameter = vehicleCode.HasValue ?
                new ObjectParameter("VehicleCode", vehicleCode) :
                new ObjectParameter("VehicleCode", typeof(long));
    
            var jobVendorCodeParameter = jobVendorCode.HasValue ?
                new ObjectParameter("JobVendorCode", jobVendorCode) :
                new ObjectParameter("JobVendorCode", typeof(long));
    
            var customerNameParameter = customerName != null ?
                new ObjectParameter("CustomerName", customerName) :
                new ObjectParameter("CustomerName", typeof(string));
    
            var contactNoParameter = contactNo != null ?
                new ObjectParameter("ContactNo", contactNo) :
                new ObjectParameter("ContactNo", typeof(string));
    
            var drivingByParameter = drivingBy.HasValue ?
                new ObjectParameter("DrivingBy", drivingBy) :
                new ObjectParameter("DrivingBy", typeof(int));
    
            var cashInHandParameter = cashInHand.HasValue ?
                new ObjectParameter("CashInHand", cashInHand) :
                new ObjectParameter("CashInHand", typeof(int));
    
            var transactionFromParameter = transactionFrom.HasValue ?
                new ObjectParameter("TransactionFrom", transactionFrom) :
                new ObjectParameter("TransactionFrom", typeof(System.DateTime));
    
            var transactionToParameter = transactionTo.HasValue ?
                new ObjectParameter("TransactionTo", transactionTo) :
                new ObjectParameter("TransactionTo", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_frm_get_Jobs_Result>("sp_frm_get_Jobs", vehicleCodeParameter, jobVendorCodeParameter, customerNameParameter, contactNoParameter, drivingByParameter, cashInHandParameter, transactionFromParameter, transactionToParameter);
        }
    
        public virtual ObjectResult<sp_frm_get_Jobs_Report_Result> sp_frm_get_Jobs_Report(Nullable<long> vehicleCode, Nullable<long> jobVendorCode, string customerName, string contactNo, Nullable<int> drivingBy, Nullable<int> cashInHand, Nullable<System.DateTime> transactionFrom, Nullable<System.DateTime> transactionTo)
        {
            var vehicleCodeParameter = vehicleCode.HasValue ?
                new ObjectParameter("VehicleCode", vehicleCode) :
                new ObjectParameter("VehicleCode", typeof(long));
    
            var jobVendorCodeParameter = jobVendorCode.HasValue ?
                new ObjectParameter("JobVendorCode", jobVendorCode) :
                new ObjectParameter("JobVendorCode", typeof(long));
    
            var customerNameParameter = customerName != null ?
                new ObjectParameter("CustomerName", customerName) :
                new ObjectParameter("CustomerName", typeof(string));
    
            var contactNoParameter = contactNo != null ?
                new ObjectParameter("ContactNo", contactNo) :
                new ObjectParameter("ContactNo", typeof(string));
    
            var drivingByParameter = drivingBy.HasValue ?
                new ObjectParameter("DrivingBy", drivingBy) :
                new ObjectParameter("DrivingBy", typeof(int));
    
            var cashInHandParameter = cashInHand.HasValue ?
                new ObjectParameter("CashInHand", cashInHand) :
                new ObjectParameter("CashInHand", typeof(int));
    
            var transactionFromParameter = transactionFrom.HasValue ?
                new ObjectParameter("TransactionFrom", transactionFrom) :
                new ObjectParameter("TransactionFrom", typeof(System.DateTime));
    
            var transactionToParameter = transactionTo.HasValue ?
                new ObjectParameter("TransactionTo", transactionTo) :
                new ObjectParameter("TransactionTo", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_frm_get_Jobs_Report_Result>("sp_frm_get_Jobs_Report", vehicleCodeParameter, jobVendorCodeParameter, customerNameParameter, contactNoParameter, drivingByParameter, cashInHandParameter, transactionFromParameter, transactionToParameter);
        }
    
        public virtual ObjectResult<sp_frm_get_OutSourceJobs_Report_Result> sp_frm_get_OutSourceJobs_Report(Nullable<long> vehicleCode, Nullable<long> jobVendorCode, string customerName, string contactNo, Nullable<int> drivingBy, Nullable<int> cashInHand, Nullable<System.DateTime> transactionFrom, Nullable<System.DateTime> transactionTo)
        {
            var vehicleCodeParameter = vehicleCode.HasValue ?
                new ObjectParameter("VehicleCode", vehicleCode) :
                new ObjectParameter("VehicleCode", typeof(long));
    
            var jobVendorCodeParameter = jobVendorCode.HasValue ?
                new ObjectParameter("JobVendorCode", jobVendorCode) :
                new ObjectParameter("JobVendorCode", typeof(long));
    
            var customerNameParameter = customerName != null ?
                new ObjectParameter("CustomerName", customerName) :
                new ObjectParameter("CustomerName", typeof(string));
    
            var contactNoParameter = contactNo != null ?
                new ObjectParameter("ContactNo", contactNo) :
                new ObjectParameter("ContactNo", typeof(string));
    
            var drivingByParameter = drivingBy.HasValue ?
                new ObjectParameter("DrivingBy", drivingBy) :
                new ObjectParameter("DrivingBy", typeof(int));
    
            var cashInHandParameter = cashInHand.HasValue ?
                new ObjectParameter("CashInHand", cashInHand) :
                new ObjectParameter("CashInHand", typeof(int));
    
            var transactionFromParameter = transactionFrom.HasValue ?
                new ObjectParameter("TransactionFrom", transactionFrom) :
                new ObjectParameter("TransactionFrom", typeof(System.DateTime));
    
            var transactionToParameter = transactionTo.HasValue ?
                new ObjectParameter("TransactionTo", transactionTo) :
                new ObjectParameter("TransactionTo", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_frm_get_OutSourceJobs_Report_Result>("sp_frm_get_OutSourceJobs_Report", vehicleCodeParameter, jobVendorCodeParameter, customerNameParameter, contactNoParameter, drivingByParameter, cashInHandParameter, transactionFromParameter, transactionToParameter);
        }
    }
}
